Books/urls.py
from django.conf.urls import url

from Books.models import Book
from . import views

app_name = 'Books'

urlpatterns = [
    # /books/
    url(r'^$', views.index, name='index'),

    # /books/register/
    url(r'^register/$', views.register, name='register'),

    # /books/<book_id>/
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),

    # /books/logout_user/
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    # /books/login_user/
    url(r'^login_user/$', views.login_user, name='login_user'),

    # /books/add
    url(r'^add/$', views.add_book, name='add_book'),

    # /books/update/2/
    url(r'^update/(?P<book_id>[0-9]+)/$', views.update_book, name='book-update'),

    # /books/delete/2
    url(r'^delete/(?P<pk>[0-9]+)/$', views.BookDelete.as_view(), name='book-delete'),

    # /books/2/return/
    url(r'^(?P<book_id>[0-9]+)/return/$', views.return_book, name='book-return'),

    # /books/2/borrow/
    url(r'^(?P<book_id>[0-9]+)/borrow/$', views.borrow_book, name='book-borrow'),

    # /books/search/ (text goes here) /
    url(r'^search/$', views.search, name='search'),

]

LibraryManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('Books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Books/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    book_logo = models.FileField(max_length=500, default='')
    taken_by = models.CharField(max_length=300)  # User's username here if book is taken

    def get_absolute_url(self):
        return reverse('Books:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ' - ' + self.author

Books/forms.py
from django.contrib.auth.models import User
from django import forms

from Books.models import Book


class BookForm(forms.ModelForm):

    taken_by = forms.CharField(required=False)

    class Meta:
        model = Book
        fields = ['title', 'author', 'book_logo']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

Books/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from .forms import *
from .models import Book


def index(request):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    my_books = Book.objects.filter(taken_by=request.user.username)
    available_books = Book.objects.filter(taken_by='')
    not_available_books = Book.objects.filter(~Q(taken_by=request.user.username), ~Q(taken_by=''))
    return render(request, 'Books/index.html',
                  {'my_books': my_books, 'user': request.user, 'available_books': available_books,
                   'not_available_books': not_available_books})


def detail(request, book_id):
    if not request.user.is_authenticated:
        return render(request, 'Books/login_form.html')
    else:
        user = request.user
        book = get_object_or_404(Book, pk=book_id)
        return render(request, 'Books/detail.html', {'book': book, 'user': user})


def register(request):
    form = UserForm(request.POST or None)

    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                my_books = Book.objects.filter(taken_by=user.username)
                available_books = Book.objects.filter(taken_by='')
                not_available_books = Book.objects.filter(~Q(taken_by=user.username), ~Q(taken_by=''))
                return render(request, 'Books/index.html',
                              {'my_books': my_books, 'user': user, 'available_books': available_books,
                               'not_available_books': not_available_books})

    return render(request, 'Books/registration_form.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('Books:login_user')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                my_books = Book.objects.filter(taken_by=user.username)
                available_books = Book.objects.filter(taken_by='')
                not_available_books = Book.objects.filter(~Q(taken_by=user.username), ~Q(taken_by=''))
                return render(request, 'Books/index.html',
                              {'my_books': my_books, 'user': user, 'available_books': available_books,
                               'not_available_books': not_available_books})
            else:
                return render(request, 'Books/login_form.html', {'error_message': 'Your account has been disabled'})
    return render(request, 'Books/login_form.html')


def add_book(request):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    else:
        form = BookForm(request.POST or None, request.FILES or None)
        form.fields.pop('taken_by')
        if form.is_valid():
            book = form.save(commit=False)
            book.book_logo = request.FILES['book_logo']
            book.save()
            return redirect('Books:detail', book.id)
        else:
            return render(request, 'Books/create_book.html', {'form': form})


def update_book(request, book_id):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    else:
        book = get_object_or_404(Book, pk=book_id)

        if request.method == "POST":
            form = BookForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                book.title = form.cleaned_data['title']
                book.author = form.cleaned_data['author']
                book.book_logo = form.cleaned_data['book_logo']
                book.taken_by = form.cleaned_data["taken_by"]
                book.save()
                return redirect('Books:detail', book.id)
        else:
            data = {'title': book.title, 'author': book.author, 'book_logo': book.book_logo, 'taken_by': book.taken_by}
            form = BookForm(initial=data)

        context = {'form': form}
        return render(request, 'Books/update_book.html', context)


class BookDelete(DeleteView):
    success_url = reverse_lazy('Books:index')
    model = Book


def return_book(request, book_id):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    else:
        book = get_object_or_404(Book, pk=book_id)
        book.taken_by = ''
        book.save()
        return redirect('Books:detail', book_id)


def borrow_book(request, book_id):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    else:
        book = get_object_or_404(Book, pk=book_id)
        book.taken_by = request.user.username
        book.save()
        return redirect('Books:detail', book_id)


def search(request):
    if not request.user.is_authenticated:
        return redirect('Books:login_user')
    else:
        query = request.GET.get("q")
        if query:
            books = Book.objects.all().filter(
                Q(title__icontains=query) |
                Q(author__icontains=query)
            ).distinct()

            my_books = books.filter(taken_by=request.user.username)
            available_books = books.filter(taken_by='')
            not_available_books = books.filter(~Q(taken_by=request.user.username), ~Q(taken_by=''))

            return render(request, 'Books/index.html',
                          {'my_books': my_books, 'user': request.user, 'available_books': available_books,
                           'not_available_books': not_available_books})
        else:
            return redirect('Books:index')

Books/templates/Books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Bookstore
        {% endblock %}
    </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Books/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header  -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Books:index' %}"> Bookstore </a>
        </div>

        <!--  Items -->
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="nav navbar-nav">
                <li class="Active">
                    <a href="{% url 'Books:index' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span> &nbsp;
                        Books
                    </a>
                </li>
            </ul>


            <!-- Search bar -->
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'Books:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>


            <ul class="nav navbar-nav navbar-right">
                {% if user.is_superuser %}
                    <li class="">
                        <a href="{% url 'Books:add_book' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> &nbsp;
                            Add Book
                        </a>
                    </li>
                {% endif %}
                <li class="">
                    <a href="{% url 'Books:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span> &nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Books/templates/Books/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Bookstore
        {% endblock %}
    </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Books/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header  -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Books:index' %}"> Bookstore </a>
        </div>

        <!--  Items -->
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'Books:register' %}">Register</a></li>
                <li class=""><a href="{% url 'Books:login_user' %}">Log In</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Books/templates/Books/book-list.html
{% for book in list %}
    <div class="col-sm-4 col-md-2 ">
        <div class="thumbnail">
            <a href="{% url 'Books:detail' book.id %}">
                <img src="{{ book.book_logo.url }}" class="img-responsive">
            </a>
            <div class="caption">
                <h2>{{ book.title }}</h2>
                <h4>{{ book.author }}</h4>

                <!-- View Details -->
                <a href="{% url 'Books:detail' book.id %}" class="btn btn-primary btn-sm"
                   role="button">View Details</a>

                <!-- Delete Album -->
                <form action="{% url 'Books:book-delete' book.id %}" method="post"
                      style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" value="{{ book.id }}"/>
                    {% if user.is_superuser %}
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    {% endif %}
                </form>


                {% if user.is_superuser %}
                    <a href="{% url 'Books:book-update' book.id %}" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-wrench"></span>
                    </a>
                {% endif %}

            </div>
        </div>
    </div>
    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

    <script>
        $(document).ready(function () {
            $(window).on('resize', function () {
                var winWidth = $(window).width();
                if (winWidth < 768) {
                    console.log('Window Width: ' + winWidth + 'class used: col-xs');
                    return 1
                } else if (winWidth <= 991) {
                    console.log('Window Width: ' + winWidth + 'class used: col-sm');
                    return 2
                } else if (winWidth <= 1199) {
                    console.log('Window Width: ' + winWidth + 'class used: col-md');
                    return 3
                } else {
                    console.log('Window Width: ' + winWidth + 'class used: col-lg');
                    return 4
                }
            });
        });
    </script>

{% endfor %}

Books/templates/Books/book_form.html
{% extends 'Books/base.html' %}

{% block title %}
    Add a new book
{% endblock %}




{% block body %}

    <div class="container-fluid">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Books/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>


{% endblock %}

Books/templates/Books/create_book.html
{% extends 'Books/base.html' %}
{% block title %}Add a new book{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Add a New Book</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'Books/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-5">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Tips on your book logo picture</h3>
                        <ul>
                            <li>Have a resolution of 512x512</li>
                            <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                            <li>Remain under the 2MB limit.</li>
                            <li>Square images look best</li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

Books/templates/Books/detail.html
{% extends 'Books/base.html' %}

{% block title %}
    Book details
{% endblock %}


{% block body %}
    <div class="container-fluid songs-container">

        <div class="row">

            <!-- Left Book Logo -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'Books:detail' book.id %}">
                            {% if book.book_logo %}
                                <img src="{{ book.book_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>

            <!-- Right Book Info -->
            <div class="col-sm-8 col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <h2>{{ book.title }}</h2>
                        <h4>{{ book.author }}</h4> <br>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <p> This book is taken by
                            {% if book.taken_by %}
                                <span class="text-danger"> <strong>{{ book.taken_by }}.</strong> </span>
                            {% else %}
                                <span class="text-success"> <strong>no one.</strong></span>
                            {% endif %}
                        </p>

                        {% if book.taken_by %}
                            {% if book.taken_by == user.username %}
                                <a href="{% url 'Books:book-return' book.id %}" class="btn btn-danger"> Return Book </a>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'Books:book-borrow' book.id %}" class="btn btn-success">Borrow</a>
                        {% endif %}
                    </div>
                </div>

            </div>

        </div>

    </div>

{% endblock %}

Books/templates/Books/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

Books/templates/Books/index.html
{% extends 'Books/base.html' %}



{% block body %}
    <div class="container-fluid">
        {% if my_books %}
            <h2>Your books</h2>
            <div class="row">
                {% with my_books as list %}
                    {% include 'Books/book-list.html' %}
                {% endwith %}
            </div>
        {% endif %}

        {% if available_books %}
            <h3> Available books </h3>
            <div class="row">
                {% with available_books as list %}
                    {% include 'Books/book-list.html' %}
                {% endwith %}
            </div>
        {% endif %}

        {% if not_available_books %}
            <h3> Not available books </h3>
            <div class="row">
                {% with not_available_books as list %}
                    {% include 'Books/book-list.html' %}
                {% endwith %}
            </div>
        {% endif %}
    </div>
{% endblock %}

Books/templates/Books/login_form.html
{% extends 'Books/base_visitor.html' %}
{% block title %}Log In{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Log In</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_username" maxlength="30" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_password" maxlength="30" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Log In</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer">
                        Don't have an account? <a href="{% url 'Books:register' %}">Click here</a> to register.
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

Books/templates/Books/registration_form.html
{% extends 'Books/base.html' %}

{% block title %}
    Register
{% endblock %}




{% block body %}

    <div class="container-fluid">

        <div class="row">


            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3> Create a new account </h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'Books/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>


        </div>


    </div>


{% endblock %}

Books/templates/Books/update_book.html
{% extends 'Books/base.html' %}
{% block title %}Update book{% endblock %}

{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Update book</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'Books/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}